### ISSUE TITLE
Add Contributing and Code of Conduct

### ISSUE THREAD

**Issue by GretaCB** [mapbox/tilejson-spec#31]
👋 Plan is to start ramping up efforts to update and document this spec. This repo is missing needed documentation for moving forward, in particular `Contributing.md` and `Code_of_Conduct.md`, which I will break out into separate PRs.

**Comment by mapsam** [comment]
These have been added, as well as a CHANGELOG documenting previous changes. Next up we'll be working through the issue queue and setting up a plan for the next version.
